/*IN THIS FILE I WANT YOU TO 
 make functions to check for PICKUP DATE FORMAT
 check for availibility period to make sure ATLEAST ONE BOX IS CHECKED
 CHECK FOR NUMBER OF STUDENTS MAKE SURE IT"S A NUMBER
 CHECK LUGGAGE AMOUNT MAKE SURE IT"S A NUMBER
 CHECK NUMBER OF TRIPS MAKE SURE IT"S A NUMBER


 CHECK FOR HOUSING AVAILABILITY
 CHECK TO MAKE SURE THAT ADDRESS HAS SOMETHING
 CHECK NUMBER OF STUDENTS ABLE TO HOST MAKE SURE IT HAS A NUMBER
 CHECK HOSTING PERIOD DATES BOTH OF THEM
 CHECK GENDER PREFERENCES MAKE SURE A VALUE IS SELECTED SEE MY REGISTRATION JS FILE FOR RADIO BUTTON VALIDATION
 */